# Generated by Django 6.1.1 on 2026-09-08 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0003_patientprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_relationships",
                        to="healthcare.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_relationships",
                        to="healthcare.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "patient"), name="unique_doctor_patient"
                    )
                ],
            },
        ),
    ]
