# Generated by Django 6.1.1 on 2026-09-08 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthcare", "0005_appointment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(max_length=500)),
                ("symptoms", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
                ("clinical_notes", models.TextField(blank=True)),
                ("record_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_medical_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to="healthcare.doctorprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to="healthcare.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to="healthcare.patientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-record_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-record_date"],
                        name="healthcare__patient_8194f7_idx",
                    ),
                    models.Index(
                        fields=["doctor", "-record_date"],
                        name="healthcare__doctor__d5b21a_idx",
                    ),
                ],
            },
        ),
    ]
